baseURL = "https://scgmlz.github.io/hugo-theme-scgdoc/"
theme = "hugo-theme-scgdoc"
themesdir = "../.."
languageCode = "en-us"
title = "My New Hugo Site"
MetaDataFormat = "toml"
canonifyURLs = true

# Code
PygmentsCodeFences = true
PygmentsUseClassic = false
PygmentsUseClasses = true
PygmentsStyle = "vs"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "James Bond"
  email = "james.bond@gmail.com"

[[params.social]]
    title = "github"
    url = "https://github.com/gamesbond"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = -190

[[menu.main]]
  name = "Documentation"
  url = "/documentation/"
  weight = -180

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -170

