baseURL = "https://scgmlz.github.io/hugo-theme-scgdoc/"
theme = "hugo-theme-scgdoc"
themesdir = "../.."
languageCode = "en-us"
title = "ProjectName"
MetaDataFormat = "toml"
canonifyURLs = true

# Code
PygmentsCodeFences = true
PygmentsUseClassic = false
PygmentsUseClasses = true
PygmentsStyle = "vs"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "James Bond"
  email = "james.bond@gmail.com"
  custom_css = ["css/exampleSite.css"]
  logo = "img/site-logo.png"

[[params.social]]
    title = "github"
    url = "https://github.com/gamesbond"

[params.authors.author1]
  name = "First Author"
  url = "http://first-author.com"
  
[params.authors.author2]
  name = "Second Author"
  url = "http://second-author.com"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = -190

[[menu.main]]
  name = "Documentation"
  url = "/documentation/"
  weight = -180

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -170

